#!/usr/bin/env python
# coding: utf-8

# In[15]:


import random
#Our data will be generated by flipping a coin 10 times and counting how many times we get heads.
def coin_trial():
    heads = 0
    for i in range(100):
        if random.random() <= 0.5:
            heads +=1
            return heads
def simulate(n):
    trials = [] 
    for i in range(n):
        trials.append(coin_trial())
        return(sum(trials)/n)
#If we perform many, many trials, we expect the average number of heads over all of our trials to approach the 50%. 
#So we performed various simulations
print(simulate(10))
print(simulate(100))
print(simulate(1000))
print(simulate(1000000))


# In[ ]:





# In[ ]:




